--liquibase formatted sql
--changeset r:1

CREATE TABLE public.tb1_expenses
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amout numeric(19,2),
    description character varying(255) COLLATE pg_catalog."default",
    expense character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tb1_expenses_pkey PRIMARY KEY (id)
)